name: Build and Release Darling

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout workflow repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential clang bison flex git cmake \
            libfuse-dev pkg-config libx11-dev libxcursor-dev \
            libxrandr-dev libxi-dev libxext-dev libxtst-dev \
            libegl1-mesa-dev libfontconfig1-dev libbsd-dev \
            libcap-dev musl-tools

      - name: Clone Darling
        run: |
          git clone --recurse-submodules https://github.com/darlinghq/darling.git

      # Dynamic build with custom tarball structure
      - name: Build Darling
        run: |
          # Change to the Darling source directory
          cd darling

          # Create the build directory and run cmake/make
          mkdir build && cd build
          cmake -DTARGET_i386=OFF -DJSC_UNIFIED_BUILD=ON ..
          make -j4
          cd ..

          # Create a temporary directory for the distribution tarball
          mkdir darling-dist
          
          # Copy the dynamic libraries into the 'lib' directory
          cp -r build/lib darling-dist/lib
          
          # Copy the binaries into the 'bin' directory
          cp -r build/bin darling-dist/bin

          # Create a basic install script
          echo '#!/bin/bash' > darling-dist/install.sh
          echo '' >> darling-dist/install.sh
          echo '# This is a placeholder install script.' >> darling-dist/install.sh
          echo '# Add your installation steps here, for example:' >> darling-dist/install.sh
          echo '# sudo cp -r bin/* /usr/local/bin/' >> darling-dist/install.sh
          echo '# sudo cp -r lib/* /usr/local/lib/' >> darling-dist/install.sh
          echo '' >> darling-dist/install.sh
          
          # Create the final tarball from the new directory structure
          tar czf "$GITHUB_WORKSPACE/darling-amd64-dynamic.tar.gz" -C . darling-dist

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: darling-binaries
          path: |
            darling-amd64-dynamic.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
