name: Build and Release Darling

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout workflow repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential clang bison flex git cmake \
            libfuse-dev pkg-config libx11-dev libxcursor-dev \
            libxrandr-dev libxi-dev libxext-dev libxtst-dev \
            libegl1-mesa-dev libfontconfig1-dev libbsd-dev \
            libcap-dev musl-tools

      - name: Clone Darling
        run: |
          git clone --recurse-submodules https://github.com/darlinghq/darling.git

      # Dynamic build
      - name: Build Darling (Dynamic)
        run: |
          cd darling
          mkdir build && cd build
          cmake -DTARGET_i386=OFF -DJSC_UNIFIED_BUILD=ON ..
          make -j4
          cd ..
          tar cxf darling-amd64-dynamic.tar.gz build/*
          mv darling-amd64-dynamic.tar.gz $GITHUB_WORKSPACE/

      # Static build
      - name: Build Darling (Static)
        run: |
          cd darling
          mkdir -p build-static
          cd build-static
          CC=musl-gcc CXX=musl-g++ LDFLAGS="-static" ../scripts/build.sh --release
          tar czf darling-amd64-static.tar.gz build/bin/*
          mv darling-amd64-static.tar.gz $GITHUB_WORKSPACE/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: darling-binaries
          path: |
            darling-amd64-dynamic.tar.gz
            darling-amd64-static.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
