name: Build and Release Darling (Static)

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential clang bison flex cmake git \
            libfuse-dev pkg-config libx11-dev libxcursor-dev \
            libxrandr-dev libxi-dev libxext-dev libxtst-dev \
            libegl1-mesa-dev libfontconfig1-dev libbsd-dev \
            libcap-dev musl-tools

      - name: Build Darling (Static)
        run: |
          git submodule update --init --recursive
          mkdir -p build
          cd build
          # Build static binaries
          cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DCMAKE_EXE_LINKER_FLAGS="-static"
          make -j$(nproc)

      - name: Package binaries
        run: |
          cd build
          tar czf darling-amd64-static.tar.gz bin/*
          mv darling-amd64-static.tar.gz $GITHUB_WORKSPACE/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: darling-amd64-static
          path: darling-amd64-static.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
